### PR TITLE
Add some sounds to menu

### PR DESCRIPTION
**Pull request by Javrel**
add music, hover, and select sounds to menu

I have also refactored the code so I can add a transition between menu and game, its so abrupt atm that you dont hear the select sound play out unless you hold the button down.

So a fade out and in transition fir gaphics added
audio fade will be in a future PR

### CODE REVIEW

**Comment by ThisUsernameWasTaken** [comment]
I'm only getting the menu music from the left channel in my headphones

**Comment by Javrel** [comment]
> I'm only getting the menu music from the left channel in my headphones

ooh Ill take a look

**Comment by Javrel** [comment]
All fixed, good spot

**Comment by Javrel** [comment]
ended up pushing some mmore changes, graphical transition between scenes
added transition code to auto load in project so its avalable in all scenes

**Comment by ThisUsernameWasTaken** [comment]
So found a new bug and I might need to go in and make different menu sounds

The Bug: 
The sound effect that triggers when you hover over an option on the menu begins to repeat indefinitely. Bug can be reproduced by going into the options menu (which stops the looping) and returning to the main menu. Upon hovering over a different option sound will once again start looping indefinitely. It was hard to notice at first because the tone sounds very similar to some of the drums in the background music.


The QA Note:
The hover over sound in the menu is too close to the sound palette of the background music and gets lost. Possible fix for both issues, remove hover sound and retain only the menu select sound.

**Comment by Javrel** [comment]
> So found a new bug and I might need to go in and make different menu sounds
> 
> The Bug: The sound effect that triggers when you hover over an option on the menu begins to repeat indefinitely. Bug can be reproduced by going into the options menu (which stops the looping) and returning to the main menu. Upon hovering over a different option sound will once again start looping indefinitely. It was hard to notice at first because the tone sounds very similar to some of the drums in the background music.
> 
> The QA Note: The hover over sound in the menu is too close to the sound palette of the background music and gets lost. Possible fix for both issues, remove hover sound and retain only the menu select sound.

ooh nice spot,  I will see how tricky it is to make it play once, at a glance theres isnt a simple option, will have to code it to only play if it hasnt yet played since entering.

something like this adapted to the multiple buttons might work...

var played = false

func myMouseEnter(event):
  if not played:
     hover.play()
     played = true

func myMouseExit(event):
   played = false

**Comment by Javrel** [comment]
@ThisUsernameWasTaken fixed it, had to reimport the sound files into the project as they default to loop mode, not the most intuitive way of it working but no code to mess with :)

**Review by ThisUsernameWasTaken — APPROVED** [review]

**Pull request merged**
